name: Bug Report
description: Report an issue or unexpected behavior
title: "Short, descriptive title of the issue"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the details below. If you have a feature request, please use the [Discussions](https://github.com/uxjulia/CrossInk/discussions/categories/ideas) feature so that issues focuses only on immediate bugs.

  - type: dropdown
    id: device-type
    attributes:
      label: Device
      description: Which device is this affecting?
      options:
        - "--- Select ---"
        - X4
        - X3
        - Seeed Sticky
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Affected Version
      description: What version of the project/library are you using? (e.g., v1.2.3, master branch commit SHA)
      placeholder: Ex. v1.2.3
    validations:
      required: true

  - type: dropdown
    id: epub-state
    attributes:
      label: EPUB Optimization
      description: Is your EPUB optimized?
      options:
        - "--- Select ---"
        - No / Not Applicable
        - Yes, using the built-in web transfer EPUB optimizer
        - Yes, using a different EPUB optimizer
        - What is an EPUB optimizer?
    validations:
      required: true

  - type: dropdown
    id: cache-state
    attributes:
      label: Cache State
      description: Have you attempted to clear any cached data?
      options:
        - "--- Select ---"
        - No / Not Applicable
        - Yes, book cache (Reader menu > Delete Book Cache)
        - Yes, reading cache (Settings > System > Clear Reading Cache)
        - Yes, device cache (SD Card > ./crosspoint folder)
        - All of the above
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Clearly list the steps necessary to reproduce the unexpected behavior.
      placeholder: |
        1. Go to '...'
        2. Select '...'
        3. Crash
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: dropdown
    id: epub-attachment
    attributes:
      label: File Provided
      description: If your issue is related to a specific file (EPUB, XTC, etc.), please make sure to attach the exact file in this ticket or email it to julia@uxj.io and reference your issue number. **_EPUBs and XTC files need to be zipped to be attached._**
      options:
        - "--- Select ---"
        - Not Applicable
        - I've attached it
        - I've emailed it
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output/Screenshots
      description: If applicable, error messages, or log output to help explain your problem. If a crash_report.txt file was generated include it here or your issue may not be addressed in a timely manner. You can drag and drop images here.
      render: shell
