/**
 * generated by fontconvert.py
 * name: ui_symbols_10
 * size: 10
 * mode: 1-bit
 * Command used: fontconvert.py ui_symbols_10 10 ../builtinFonts/source/NotoSymbols/NotoSansSymbols2-Regular.ttf --no-default-intervals --additional-intervals 0x23FB,0x23FB
 */
#pragma once
#include "EpdFontData.h"

static const uint8_t ui_symbols_10Bitmaps[41] = {
    0x00, 0xE0, 0x00, 0x38, 0x00, 0x0E, 0x00, 0x63, 0x8C, 0x3C, 0xE7, 0x0E, 0x38, 0xE7, 0x0E, 0x1D,
    0xC3, 0x87, 0x60, 0xE1, 0xD8, 0x00, 0x36, 0x00, 0x0D, 0x80, 0x07, 0x70, 0x01, 0xDC, 0x00, 0xE3,
    0x80, 0x78, 0x78, 0x7C, 0x0F, 0xFE, 0x01, 0xFE, 0x00,
};

static const EpdGlyph ui_symbols_10Glyphs[] = {
    { 18, 18, 298, 0, 17, 41, 0 }, // U+23FB
};

static const EpdUnicodeInterval ui_symbols_10Intervals[] = {
    { 0x23FB, 0x23FB, 0x0 },
};

static constexpr EpdFontData ui_symbols_10 = {
    ui_symbols_10Bitmaps,
    ui_symbols_10Glyphs,
    ui_symbols_10Intervals,
    1,
    35,
    23,
    -14,
    false,
    nullptr,
    0,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    0,
    0,
    0,
    0,
    nullptr,
    0,
};
