"""Build the CrossInk web portal: compose pages from shared templates/assets,
minify, gzip, and emit the C headers that the firmware serves from flash.

Source of truth lives under web/:
  web/templates/base.html  - shared chrome (head, nav, footer, logo)
  web/pages/<slug>.{html,css,js} - per-page body, styles, script
  web/assets/style.css     - shared theme, served once at /style.css
  web/assets/logo.png      - drop logo, served once at /logo.png

Outputs land in src/network/html/ with the identifiers the C++ already uses.
No third-party dependencies (runs inside the PlatformIO pre-build step)."""
import os
import re
import gzip
import hashlib

try:
    ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
except NameError:
    # PlatformIO may exec this pre-script without a __file__; it runs from the
    # project root, so fall back to the current working directory.
    ROOT = os.getcwd()
WEB = os.path.join(ROOT, "web")
OUT = os.path.join(ROOT, "src", "network", "html")
JS_OUT = os.path.join(OUT, "js")

# slug -> (generated identifier, <title>, active nav, extra <head> markup)
PAGES = {
    "home":     ("HomePageHtml",     "CrossInk",                   "home",     ""),
    "files":    ("FilesPageHtml",    "Files - CrossInk",           "files",    '  <script src="/js/jszip.min.js"></script>'),
    "settings": ("SettingsPageHtml", "Settings - CrossInk Reader", "settings", ""),
    "fonts":    ("FontsPageHtml",    "Fonts - CrossInk",           "fonts",    ""),
}

PRESERVE_TAGS = "pre|code|textarea|script|style"

def minify_html(html):
    blocks = []
    def stash(m):
        blocks.append(m.group(0))
        return f"__BLK_{len(blocks)-1}__"
    html = re.sub(rf"<({PRESERVE_TAGS})[\s\S]*?</\1>", stash, html, flags=re.IGNORECASE)
    html = re.sub(r"<!--.*?-->", "", html, flags=re.DOTALL)
    html = re.sub(r">\s+<", "><", html)
    html = re.sub(r"\s+", " ", html)
    for i, b in enumerate(blocks):
        html = html.replace(f"__BLK_{i}__", b)
    return html.strip()

def minify_css(css):
    css = re.sub(r"/\*.*?\*/", "", css, flags=re.DOTALL)
    return re.sub(r"\s+", " ", css).strip()

def render(template, values):
    # Single pass so substituted content is never re-scanned for placeholders.
    return re.sub(r"{{\s*(\w+)\s*}}", lambda m: values[m.group(1)], template)

def emit_header(path, ident, data, *, original_len=None):
    """Write a generated header. When original_len is given the payload is
    treated as gzip-compressed (NAMECompressedSize/NAMEOriginalSize); otherwise
    it is raw bytes (NAMESize)."""
    with open(path, "w", encoding="utf-8") as h:
        h.write("// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY\n\n")
        h.write("#pragma once\n#include <cstddef>\n\n")
        h.write(f"constexpr char {ident}[] PROGMEM = {{\n")
        for i in range(0, len(data), 16):
            row = ", ".join(f"0x{b:02x}" for b in data[i:i+16])
            h.write(f"  {row},\n")
        h.write("};\n\n")
        etag = hashlib.sha256(data).hexdigest()
        h.write(f'constexpr char {ident}ETag[] = "\\\"{etag}\\\"";\n')
        if original_len is None:
            h.write(f"constexpr size_t {ident}Size = {len(data)};\n")
        else:
            h.write(f"constexpr size_t {ident}CompressedSize = {len(data)};\n")
            h.write(f"constexpr size_t {ident}OriginalSize = {original_len};\n")

def read(*parts):
    with open(os.path.join(*parts), encoding="utf-8") as f:
        return f.read()

def emit_gzip(path, ident, text):
    gz = gzip.compress(text.encode("utf-8"), compresslevel=9, mtime=0)
    emit_header(path, ident, gz, original_len=len(text))
    return len(text), len(gz)

# Cache-busting version derived from the shared assets' content.
style_css = read(WEB, "assets", "style.css")
logo_png = open(os.path.join(WEB, "assets", "logo.png"), "rb").read()
v = hashlib.sha1(style_css.encode("utf-8") + logo_png).hexdigest()[:8]

base = read(WEB, "templates", "base.html")

for slug, (ident, title, active, head_extra) in PAGES.items():
    page_css = read(WEB, "pages", f"{slug}.css")
    page_html = read(WEB, "pages", f"{slug}.html")
    page_js = read(WEB, "pages", f"{slug}.js").strip()
    script = f"<script>\n{page_js}\n</script>" if page_js else ""
    values = {
        "title": title, "v": v, "head_extra": head_extra,
        "styles": page_css, "body": page_html, "script": script,
        "cls_home": "", "cls_files": "", "cls_settings": "", "cls_fonts": "",
    }
    values[f"cls_{active}"] = ' class="active"'
    html = minify_html(render(base, values))
    orig, comp = emit_gzip(os.path.join(OUT, f"{ident}.generated.h"), ident, html)
    print(f"{ident:18} {orig:>7}B -> {comp:>6}B gz")

# Shared CSS (served once at /style.css).
orig, comp = emit_gzip(os.path.join(OUT, "StyleCss.generated.h"), "StyleCss", minify_css(style_css))
print(f"{'StyleCss':18} {orig:>7}B -> {comp:>6}B gz")

# Logo (already PNG-compressed: served raw at /logo.png).
emit_header(os.path.join(OUT, "LogoPng.generated.h"), "LogoPng", logo_png)
print(f"{'LogoPng':18} {len(logo_png):>7}B raw")

# jszip stays a separate cached asset; pre-minified, so just gzip it.
jszip = read(JS_OUT, "jszip.min.js")
orig, comp = emit_gzip(os.path.join(JS_OUT, "jszip_minJs.generated.h"), "jszip_minJs", jszip)
print(f"{'jszip_minJs':18} {orig:>7}B -> {comp:>6}B gz")
