// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define LEXENDDECA_8_FONT_ID (1235804810)
#define LEXENDDECA_9_FONT_ID (-1793073765)
#define LEXENDDECA_10_FONT_ID (989607746)
#define LEXENDDECA_12_FONT_ID (1378801523)
#define LEXENDDECA_14_FONT_ID (1261118480)
#define LEXENDDECA_16_FONT_ID (-407738734)
#define LEXENDDECA_18_FONT_ID (-2124313022)
#define LEXENDDECA_20_FONT_ID (2015188046)
#define CHAREINK_8_FONT_ID (-478039160)
#define CHAREINK_9_FONT_ID (-1635849624)
#define CHAREINK_10_FONT_ID (-1895610281)
#define CHAREINK_12_FONT_ID (-1009812368)
#define CHAREINK_14_FONT_ID (367778404)
#define CHAREINK_16_FONT_ID (-895687199)
#define CHAREINK_18_FONT_ID (-2013346982)
#define CHAREINK_20_FONT_ID (-744100586)
#define BITTER_8_FONT_ID (-450736356)
#define BITTER_9_FONT_ID (-1407833974)
#define BITTER_10_FONT_ID (584177220)
#define BITTER_12_FONT_ID (-1786472669)
#define BITTER_14_FONT_ID (-595183445)
#define BITTER_16_FONT_ID (422600567)
#define BITTER_18_FONT_ID (-536063611)
#define BITTER_20_FONT_ID (-1986600437)
#define UI_10_FONT_ID (971628580)
#define UI_12_FONT_ID (1618379298)
#define SMALL_FONT_ID (1851589260)

// Font ID 0 is reserved as the "not found" sentinel.
// Guard against any hash accidentally producing 0.
static_assert(LEXENDDECA_8_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_9_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_20_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(CHAREINK_8_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(CHAREINK_9_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(CHAREINK_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(CHAREINK_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(CHAREINK_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(CHAREINK_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(CHAREINK_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(CHAREINK_20_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(BITTER_8_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(BITTER_9_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(BITTER_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(BITTER_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(BITTER_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(BITTER_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(BITTER_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(BITTER_20_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
